### PR TITLE
Differentiated cancel message

### PR DESCRIPTION
**Pull request by jho5245**
I'm sorry but this was another one I urgently want to fix.
I've tested this. as you said this wasn't a bug. and now fixed it!

### CODE REVIEW

**Comment by jho5245** [comment]
But there's CREATE and BUY (PURCHASE) this should be separated

**Comment by Ghost-chu** [comment]
Yes, this is a history issue.
But you should check the two location in same world before check the distance.

And if... better performance, every tick is we should to gain.

**Comment by jho5245** [comment]
eh... I can't understand correctly, can you explain more? "every tick is we should to gain."

**Comment by Ghost-chu** [comment]
That mean: Every tick is important
20 ticks=1s

**Comment by jho5245** [comment]
hmm.. then should I remove the separate cancel message output? without this, people may confuse with output message.

**Comment by Ghost-chu** [comment]
No just edit the switch to if, and check the world before the check distance

**Comment by jho5245** [comment]
oh, okay

**Comment by jho5245** [comment]
check if world is same first, and changed switch to if

**Comment by Ghost-chu** [comment]
Thanks for your hard work :)
By the way, i'm glad to invite you help me develop the plugin together, just read more sources and when i think you have enough power to commit directly in master repo, i will give you this repo permission :)

**Comment by jho5245** [comment]
o.O I'll do my best to make this plugin more awesome!

**Comment by Ghost-chu** [comment]
Oof i forgot tell you.
If modify the language/config file, you must write config/messages update method.


It on QuickShop#updateConfig
And MsgUtil#updateMessages(i think...)


And don't forget modify config.yml and messages_en.yml files config-version in the resources folder.


You shouldn't update other languages files. Becuase they will process by OneSkyApp platform to update them.



---Original---

**Comment by jho5245** [comment]
I'll update it

**Pull request merged**
