### PR TITLE
Improved README with some HTML

### PR DESCRIPTION
**Pull request by Chris6ix**
Changes:

-Made KaiKikuchi's QuickShop upstream repository link look better
-Made Support category look a lot better with HTML
-Made Downloads category look a lot better using HTML (I had to remove "Relatev" because I couldn't find a logo that worked...and the resource itself was very outdated...so I guess it wasn't used/needed anymore)
-Removed Jenkins link for stable builds as they are provided via the other sites
-Removed 2 small Bstats badges because this info is already in the big graph

If you want to see exactly how it looks before merging: [Link](https://github.com/Chris6ix/QuickShop-Reremake/blob/master/README.md)
Tell me how you guys like it :)

### CODE REVIEW

**Comment by Ghost-chu** [comment]
Maybe you can use Favicon icon instead for downloads icons.

Because these icon looks really strange...

**Comment by Chris6ix** [comment]
It isn't a good idea to use Favicon here as they are very small and low resolution...
Here is the Favicon from Spigot so you see what i mean [Link](https://www.spigotmc.org/favicon.ico)

I have adjusted the dimensions and positions of the downloads icons a little so they look better

I have also saved every image locally here on the repository as this improves the loading of these images on slower internet connections (Especially for the MCBBS Logo)

Tell me how you like it now :)
If you have anything you don't like about it, then please specify exactly what it is

**Comment by sandtechnology** [comment]
I prefer to use table to do it, for example:
| <a href="https://discord.gg/bfefw2E"/>  | <a href="https://github.com/Ghost-chu/QuickShop-Reremake/issues"> |
| :-: | :-: |
| **Discord**: | **Github Issues** |
```
| <a href="https://discord.gg/bfefw2E"/> <img src="/.github/icons/Discord.svg" width="100" height="100" /> | <a href="https://github.com/Ghost-chu/QuickShop-Reremake/issues"><img src="/.github/icons/Github.png" width="100" height="100" /> |
| :-: | :-: |
| **Discord**: | **Github Issues** |
```

**Comment by Chris6ix** [comment]
Like this @sandtechnology?

**Comment by sandtechnology** [comment]
Yes, that much better for reader, how about @Ghost-chu ?

**Comment by Chris6ix** [comment]
/\ 
I also changed current Java version to 8-16 because Java 17 isn't even out yet...

@Ghost-chu How do you like the current README? ([Link](https://github.com/Ghost-chu/QuickShop-Reremake/blob/Chris6ix-Improved-README/README.md))

**Comment by Ghost-chu** [comment]
> /\
> I also changed current Java version to 8-16 because Java 17 isn't even out yet...
> 
> @Ghost-chu How do you like the current README? ([Link](https://github.com/Ghost-chu/QuickShop-Reremake/blob/Chris6ix-Improved-README/README.md))

Good enough ^ ^

**Pull request merged**
