### PR TITLE
Optimizing/Simplifying/Null-safety/Final-modifiers [Not in Scope]

### PR DESCRIPTION
**Pull request by portlek**
The PR is about refactoring messy and ununderstandable codes.

The PR includes;

> Null-safety on commands, events, listeners, economy, database.
> Final modifiers on commands, events, listeners, economy, database.
> Simplifying on commands, events, listeners, economy, database.
> Some `TODO` and `FIXME` notes.

It can solve;

> Possible null point exceptions at the sections.

The PR does not include:

> Feature changes.
> Functional changes.
> The plugin mechanism.

Feature of the PR;

> It will refactor the main class of the plugin.
> It will refactor classes that are in the `Shop` package.

Good luck have fun to code reviewers :)

Thank you.

### CODE REVIEW

**Comment by Ghost-chu** [comment]
can't use final becuase it will broken the plugman support and plugin built-in reload.

**Comment by portlek** [comment]
About finals on the instances, ok I can change it, but in the @Nullable case I can say that if one thing can be null it can bu also Not null but if one thing is not null it can't be nullable so, Nullable includes  NotNull I think It won't break anything about the plugin.

**Comment by portlek** [comment]
I will test the final modifiers with the PluginMan plugin.

**Comment by portlek** [comment]
Btw, If the finals break the system, the problem is the plugin instead of the finals. If there is an issue that I will fix it also.

**Comment by portlek** [comment]
I tested with PlugMan + normal /reload commands times and times but It does not cause any error.

**Comment by Ghost-chu** [comment]
Need a deep test, some class will create new obj, so if have final mark, maybe cause unknown issue.

**Comment by portlek** [comment]
Ok, I will test it 3-5 days.

**Comment by portlek** [comment]
The `42abcbd` commit is for #225

**Comment by portlek** [comment]
This P.R. will open after current bug fixed.

**Pull request merged**
