### PR TITLE
Tax never should failed.

### PR DESCRIPTION
**Pull request by Ghost-chu**

### CODE REVIEW

**Comment by sandtechnology** [comment]
But tax deposit failed should be a bug or error, in original version also work like this.....

**Comment by sandtechnology** [comment]
A solution for such error is add a option like "use-tax-account" and when disable just let tax account is NULL.

**Comment by Ghost-chu** [comment]
Not in reremake, we didn't care tax success or failure.

**Comment by Ghost-chu** [comment]
use-tax-account is stupid, set tax-account to null or empty to disable should be okay

**Pull request merged**
