### PR TITLE
New Release

### PR DESCRIPTION
**Pull request by sandtechnology**

### CODE REVIEW

**Review by Ghost-chu — CHANGES_REQUESTED** [review]
This will quite break the feature of this command.

Try spilt the task to different ticks.

**Comment by Ghost-chu** [comment]
Before we find the cause of strange NPSB char, I don't recommend to merge this PR.

**Comment by Ghost-chu** [comment]
minedown seems is thread-safe, we don't need prevent async access.

**Comment by sandtechnology** [comment]
> 
> 
> Before we find the cause of strange NPSB char, I don't recommend to merge this PR.

Please check discord chat history

**Comment by sandtechnology** [comment]
> 
> 
> minedown seems is thread-safe, we don't need prevent concurrent access.

Please check the source code of minedown

**Comment by sandtechnology** [comment]
> 
> 
> This will quite break the feature of this command.(/qs info)
> 
> Try spilt the task to different ticks.

For large shop amount (1000+) which spreading in different chunk, is a nightmare for counting this, we can only provide the loaded shop information

**Comment by Ghost-chu** [comment]
> > This will quite break the feature of this command.(/qs info)
> > Try spilt the task to different ticks.
> 
> For large shop amount (1000+) which spreading in different chunk, is a nightmare for counting this, we can only provide the loaded shop information

But this will completely destory this command. For small servers.

It is impossible to let owner teleport target chunks and to loading shops.

**Comment by sandtechnology** [comment]
> 
> 
> > > This will quite break the feature of this command.(/qs info)
> > > Try spilt the task to different ticks.
> > 
> > 
> > For large shop amount (1000+) which spreading in different chunk, is a nightmare for counting this, we can only provide the loaded shop information
> 
> But this will completely destory this command. For small servers.
> 
> It is impossible to let owner teleport target chunks and to loading shops.

But actually nobody using that command : D

**Review by Ghost-chu — APPROVED** [review]

**Pull request merged**
