### PR TITLE
Implement VirtualDisplayItem

### PR DESCRIPTION
**Pull request by sandtechnology**
Structure change: move DisplayItem related class to DisplayItem package
(org.maxgamer.quickshop.Shop->org.maxgamer.quickshop.Shop.DisplayItem)

### CODE REVIEW

**Comment by portlek** [comment]
The P.R. contains a lot of works. Thanks for it but, reviewing the 202 changed files will be painfull could you open p.r. as little as possible? And just do what you say, don't do other things like the indents.

**Comment by sandtechnology** [comment]
> 
> 
> The P.R. contains a lot of works. Thanks for it but, reviewing the 202 changed files will be painfull could you open p.r. as little as possible? And just do what you say, don't do other things like the indents.

Sorry, it's cause by auto-reformat code, I will make it as smallest as possible

**Comment by portlek** [comment]
By the way, we don't use the master branch directly, please change your target branch to v4.

**Comment by portlek** [comment]
Save your changes to another file, and reset your fork. After doing that, copy your P.R. changes to the files that were reset.

**Comment by portlek** [comment]
For resetting the forks you can read this;
https://stackoverflow.com/questions/9646167/clean-up-a-fork-and-restart-it-from-the-upstream

**Comment by sandtechnology** [comment]
> 
> 
> For resetting the forks you can read this;
> https://stackoverflow.com/questions/9646167/clean-up-a-fork-and-restart-it-from-the-upstream

thanks, I will rework it.

**Pull request closed without merging**
